/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlePractice;

public class Library {
	
	private String someStr;
	private String anotherStr;
	
	public Library() {
		
	}
	
	public boolean someLibraryMethod() {
        return true;
    }
	
    
	public String getAnotherStr() {
		return anotherStr;
	}

	public void setAnotherStr(String anotherStr) {
		this.anotherStr = anotherStr;
	}

	public String getSomeStr() {
		return someStr;
	}

	public void setSomeStr(String someStr) {
		this.someStr = someStr;
	}

	
}
