/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlePractice;

public class Library {
	
	private String someStr;
	
	public boolean someLibraryMethod() {
        return true;
    }
	
    public String getSomeStr() {
		return someStr;
	}

	public void setSomeStr(String someStr) {
		this.someStr = someStr;
	}

	
}
