/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradlePractice;

import org.junit.Test;

import gradlePractice.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library("somestr");
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
